#!/usr/bin/env python3
"""
prompt_template.py — render and verify image prompts from one shared template.

The store banner is generated by two runbooks: `/autocreate-finalize` makes it
first, and `/store-screenshots` makes it again only when no valid banner exists.
"Use the same prompt" written into two runbooks did not hold: each agent
"adapted" the instructions in its own words, and the two banners drifted in
framing, ball placement and lower-edge treatment. The fix is to stop asking an
agent to write the prompt at all. The prompt lives once, as a template in
`.claude/skills/store-screenshots/references/campaign-prompts.md`, and an agent
only supplies the game-specific values for its `{{placeholders}}`.

  list    the template ids in a file and each one's placeholders
  render  fill one template from --set name=value pairs and write the prompt
  check   prove an existing prompt file is that template with only the
          placeholders filled in (whitespace-insensitive); names the first
          sentence that was reworded, dropped or added

A template is a fenced block whose info string is `prompt <id>`:

    ```prompt banner-character
    One continuous ... {{environment}} ...
    ```

Usage:
  python3 tools/prompt_template.py list \\
      --template .claude/skills/store-screenshots/references/campaign-prompts.md
  python3 tools/prompt_template.py render --template <file> --id banner-character \\
      --set environment="..." --set objects="..." --out production/store-art/banner-prompt.txt
  python3 tools/prompt_template.py check --template <file> --id banner-character \\
      --prompt production/store-art/banner-prompt.txt

Exit codes: 0 = OK/PASS, 1 = FAIL (check) or missing values (render), 2 = bad invocation.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

FENCE_RE = re.compile(r"^```prompt[ \t]+([A-Za-z0-9_.-]+)[ \t]*\n(.*?)^```[ \t]*$",
                      re.M | re.S)
PLACEHOLDER_RE = re.compile(r"\{\{\s*([A-Za-z0-9_]+)\s*\}\}")
# One placeholder carries a subject list or a palette, never a second prompt.
DEFAULT_MAX_FILL = 500


class TemplateError(Exception):
    """A template or a filled prompt that cannot be used."""


def squeeze(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def load_templates(path: Path) -> dict[str, str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise TemplateError(f"cannot read template file {path}: {exc}") from exc
    templates: dict[str, str] = {}
    for match in FENCE_RE.finditer(text):
        tid = match.group(1)
        if tid in templates:
            raise TemplateError(f"{path}: template id {tid!r} is defined twice")
        templates[tid] = squeeze(match.group(2))
    if not templates:
        raise TemplateError(f"{path}: no ```prompt <id> blocks found")
    return templates


def template_for(path: Path, tid: str) -> str:
    templates = load_templates(path)
    if tid not in templates:
        raise TemplateError(f"{path}: no template {tid!r}; have {', '.join(sorted(templates))}")
    return templates[tid]


def placeholders(template: str) -> list[str]:
    seen: list[str] = []
    for name in PLACEHOLDER_RE.findall(template):
        if name not in seen:
            seen.append(name)
    return seen


def validate_value(name: str, value: str, max_fill: int) -> str:
    value = squeeze(value)
    if not value:
        raise TemplateError(f"{{{{{name}}}}} is empty")
    if "{{" in value or "}}" in value:
        raise TemplateError(f"{{{{{name}}}}} still contains a placeholder: {value[:80]!r}")
    if len(value) > max_fill:
        raise TemplateError(
            f"{{{{{name}}}}} is {len(value)} characters (limit {max_fill}); a placeholder "
            "names this game's subjects, it does not carry extra instructions")
    return value


def render(template: str, values: dict[str, str], max_fill: int = DEFAULT_MAX_FILL) -> str:
    needed = placeholders(template)
    missing = [n for n in needed if n not in values]
    if missing:
        raise TemplateError("missing values for: " + ", ".join(f"{{{{{n}}}}}" for n in missing))
    unknown = [n for n in values if n not in needed]
    if unknown:
        raise TemplateError("the template has no placeholder(s): " + ", ".join(unknown))
    clean = {n: validate_value(n, v, max_fill) for n, v in values.items()}
    return PLACEHOLDER_RE.sub(lambda m: clean[m.group(1)], template)


def _chunks(template: str) -> tuple[list[str], list[str]]:
    """Literal chunks and the placeholder names between them."""
    return PLACEHOLDER_RE.split(template)[0::2], PLACEHOLDER_RE.split(template)[1::2]


def _pattern(literals: list[str], names: list[str], upto: int | None = None) -> str:
    parts: list[str] = []
    stop = len(literals) if upto is None else upto
    for i in range(stop):
        parts.append(re.escape(literals[i]))
        if i < len(names) and i < stop - 1:
            parts.append("(.+?)")
    return "".join(parts)


def check(template: str, prompt: str, max_fill: int = DEFAULT_MAX_FILL) -> dict[str, str]:
    """Return the placeholder values if `prompt` is `template` filled in; raise otherwise."""
    prompt = squeeze(prompt)
    literals, names = _chunks(template)
    full = re.fullmatch(_pattern(literals, names), prompt, re.S)
    if full:
        values: dict[str, str] = {}
        for name, value in zip(names, full.groups()):
            value = validate_value(name, value, max_fill)
            if name in values and values[name] != value:
                raise TemplateError(f"{{{{{name}}}}} is filled two different ways")
            values[name] = value
        return values
    # Find the first literal passage the prompt no longer carries verbatim.
    for upto in range(1, len(literals) + 1):
        if not re.match(_pattern(literals, names, upto), prompt, re.S):
            expected = literals[upto - 1].strip() or "(end of prompt)"
            raise TemplateError(
                "the prompt departs from the template at: "
                f"{expected[:160]!r}{'…' if len(expected) > 160 else ''}")
    raise TemplateError("the prompt has extra text after the template's final sentence")


def parse_sets(pairs: list[str], files: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for pair in pairs:
        if "=" not in pair:
            raise TemplateError(f"--set {pair!r}: expected name=value")
        name, value = pair.split("=", 1)
        values[name.strip()] = value
    for pair in files:
        if "=" not in pair:
            raise TemplateError(f"--set-file {pair!r}: expected name=path")
        name, path = pair.split("=", 1)
        try:
            values[name.strip()] = Path(path).read_text(encoding="utf-8")
        except OSError as exc:
            raise TemplateError(f"--set-file {name}: cannot read {path}: {exc}") from exc
    return values


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="cmd", required=True)

    ls = sub.add_parser("list", help="template ids and their placeholders")
    ls.add_argument("--template", required=True)

    rd = sub.add_parser("render", help="fill a template and write the prompt")
    rd.add_argument("--template", required=True)
    rd.add_argument("--id", required=True)
    rd.add_argument("--set", action="append", default=[], metavar="NAME=VALUE")
    rd.add_argument("--set-file", action="append", default=[], metavar="NAME=PATH")
    rd.add_argument("--out", help="write here (default: stdout)")
    rd.add_argument("--max-fill", type=int, default=DEFAULT_MAX_FILL)

    ck = sub.add_parser("check", help="verify a prompt file against a template")
    ck.add_argument("--template", required=True)
    ck.add_argument("--id", required=True)
    ck.add_argument("--prompt", required=True, help="the prompt file that was (or will be) sent")
    ck.add_argument("--max-fill", type=int, default=DEFAULT_MAX_FILL)

    args = parser.parse_args(argv)
    try:
        if args.cmd == "list":
            for tid, body in load_templates(Path(args.template)).items():
                names = placeholders(body)
                print(f"{tid}: " + (", ".join(names) if names else "(no placeholders)"))
            return 0
        template = template_for(Path(args.template), args.id)
        if args.cmd == "render":
            prompt = render(template, parse_sets(args.set, args.set_file), args.max_fill)
            if args.out:
                Path(args.out).parent.mkdir(parents=True, exist_ok=True)
                Path(args.out).write_text(prompt + "\n", encoding="utf-8")
                print(f"✅ {args.id} → {args.out} ({len(prompt)} chars)")
            else:
                print(prompt)
            return 0
        try:
            prompt_text = Path(args.prompt).read_text(encoding="utf-8")
        except OSError as exc:
            print(f"❌ cannot read {args.prompt}: {exc}", file=sys.stderr)
            return 2
        values = check(template, prompt_text, args.max_fill)
        print(f"✅ PASS — {args.prompt} is template {args.id!r} with "
              f"{len(values)} placeholder(s) filled")
        return 0
    except TemplateError as exc:
        print(f"❌ {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
